package org.pih.hivmigration.common.code;

import java.util.Arrays;
import java.util.List;

/**
 * This corresponds to the hiv_exam_ois.oi values
 */
public enum OI implements CodedValue {

	ACUTE_DIARRHEA,
	ANXIETY,
	BACTERIAL_DIARRHEA,
	BACTERIAL_MENINGITIS,
	BACTERIAL_PNEUMONIA,
	CANDIDIARIS_ESOPHAGITIS,
	CANDIDIARIS_OROPHARYNGEAL,
	CANDIDIARIS_OTHER,
	CANDIDIARIS_VAGINAL,
	CHANCROID,
	CHRONIC_DIARRHEA,
	CRYPTOCOCCUS_MENINGITIS,
	DEPRESSION,
	DIABETES,
	DYSENTERY,
	DYSPHAGIA,
	ENCEPHALOPATHY,
	EXTRAPULMONARY_TB,
	GENITAL_ULCERATIONS,
	GENITO_URINARY_SYPHILIS,
	HERPES_ZOSTER,
	HIV,
	HSV,
	HYPERTENSION,
	KAPOSIS_SARCOMA,
	LGV,
	LYMPHOMA,
	MALARIA,
	MENINGITIS,
	NEUROLOGIC_SYPHILIS,
	NON_GENITO_URINARY_SYPHILIS,
	NONE,
	OTHER,
	OTHER_DIARRHEA,
	OTHER_ENCEPHALOPATHY,
	OTHER_MENINGITIS,
	OTHER_NEURO,
	OTHER_PNEUMONIA,
	OTHER_RASH,
	PARASITIC_DIARRHEA,
	PCP_PNEUMONIA,
	PID,
	PNEUMOPATHY,
	PRURIGO_NODULAIRIS,
	PRURITIS,
	PSYCHOSIS,
	PULMONARY_TB,
	SEIZURES,
	SHINGLES,
	STD,
	TB_ENTERITIS,
	TB_MENINGITIS,
	THRUSH,
	TOXOPLASMOSIS,
	TRICHOMONIASIS,
	TUBERCULOMA,
	TUBERCULOSIS,
	TYPHOID,
	VAGINAL_URETHRAL_DISCHARGE,
	VAGINAL_URETHRAL_GC,
	VAGINAL_URETHRAL_OTHER,
	WARTS,
	WASTING,
	WEIGHT_LOSS;

	@Override
	public List<String> getValues() {
		return Arrays.asList(name().toLowerCase());
	}
}
