package org.pih.hivmigration.common.code;

import java.util.Arrays;
import java.util.List;

/**
 * This corresponds to the hiv_exam_system_status.condition values
 */
public enum OtherOrderable implements CodedValue {

	ABSTINENCE,
	AMPHOTERICINE_B,
	ARV_REGIMEN,
	ARV_REGIMEN_OTHER,
	ARV_START_DATE,
	ARVS,
	CHANGE_ARVS,
	CHANGE_ARVS_OTHER,
	CHLOROQUINE,
	CONDOM,
	DEPO_PROVERA,
	FAMILY_PLANNING,
	FAMILY_PLANNING_OTHER1,
	FAMILY_PLANNING_OTHER2,
	FINANCIAL_AID,
	FIX_HOUSE_AID,
	FLUCONAZOLE,
	FLUCONAZOLE_CONTINUE,
	FLUCONAZOLE_DOSE,
	FLUCONAZOLE_HIGH,
	FLUCONAZOLE_LOW,
	FLUCONAZOLE_LOW_STOPPED,
	FLUCONAZOLE_NUM_PER_DAY,
	FLUCONAZOLE_REASON,
	FUNERAL_AID,
	HOUSE_ASSISTANCE,
	INH_PROPHYLAXIS,
	INH_PROPHYLAXIS_CONTINUE,
	INH_PROPHYLAXIS_DOSE,
	INH_PROPHYLAXIS_NUM_PER_DAY,
	INH_PROPHYLAXIS_REASON,
	INH_PROPHYLAXIS_STOPPED,
	MOSQUITO_NET,
	NNTRI_PI,
	NO_FAMILY_PLANNING,
	NORPLANT,
	NTRI1,
	NTRI2,
	NUTRITIONAL_AID,
	ORAL_CONTRACEPTIVE,
	OTHER_OI,
	OTHER_PROPHYLAXIS,
	OTHER_PROPHYLAXIS_CONTINUE,
	OTHER_PROPHYLAXIS_DOSE,
	OTHER_PROPHYLAXIS_NUM_PER_DAY,
	OTHER_PROPHYLAXIS_REASON,
	OTHER_TREATMENT,
	PROFESSIONAL_TRAINING,
	PROPHYLAXIS,
	PROPHYLAXIS_STOPPED,
	SCHOOL_AID,
	SOCIAL_ASSISTANCE_OTHER,
	START_ARVS,
	TB_START_DATE,
	TB_TREATMENT,
	TMP_SMX_PROPHYLAXIS,
	TMP_SMX_PROPHYLAXIS_CONTINUE,
	TMP_SMX_PROPHYLAXIS_DOSE,
	TMP_SMX_PROPHYLAXIS_NUM_PER_DAY,
	TMP_SMX_PROPHYLAXIS_REASON,
	TMP_SMX_PROPHYLAXIS_STOPPED,
	TMP_SMX_TREATMENT,
	TRANPORTATION_AID,
	TUBAL_LIGATION,
	VASECTOMY,
	VOLUNTARY_COUNSELING_AND_TESTING,
	WORK_TRAINING;

	@Override
	public List<String> getValues() {
		return Arrays.asList(name().toLowerCase());
	}
}
