package org.pih.hivmigration.common.code;

/**
 * This corresponds to the hiv_exam_who_staging_criteria.criterium values
 */
public enum WhoStagingCriteria implements CodedValue {

	ACUTE_NECROTIZING_ULCERATIVE_STOMATITIS_GINGIVITIS_PERIODONTITIS,
	ANGULAR_CHEILITIS,
	ASYMPTOMATIC,
	CANDIDIASIS_OF_ESOPHAGUS_TRACHEA_BRONCHI_LUNGS,
	EXTRAPULMONARY_TB,
	FUNGAL_NAIL_INFECTION,
	HERPES_ZOSTER,
	HIV_WASTING,
	ORAL_HAIRY_LEUKOPLAKIA,
	PAPULAR_PRURITIC_ERUPTIONS,
	PERSISTENT_GENERALIZED_LYMPHADENOPATHY,
	PERSISTENT_ORAL_CANDIDIASIS,
	PNEUMOCYSTIS_PNEUMONIA,
	PULMONARY_TUBERCULOSIS_CURRENT,
	RECURRENT_ORAL_ULCERATION,
	RECURRENT_SEVERE_BACTERIAL_PNEUMONIA,
	RECURRENT_UPPER_RESPITORY_INFECTIONS,
	SEBORRHOEIC_DERMATITIS,
	SEVERE_BACTERIAL_INFECTIONS,
	UNEXPLAINED_ANAEMIA_NEUTROPAENIA_THROMBOCYTOPAENIA_OVER_1_MONTH,
	UNEXPLAINED_CHRONIC_DIARRHEA_OVER_1_MONTH,
	UNEXPLAINED_PERSISTENT_FEVRE,
	UNEXPLAINED_WEIGHT_LOSS_OVER_10_PERCENT,
	UNEXPLAINED_WEIGHT_LOSS_UNDER_10_PERCENT;

	public String getValue() {
		return name().toLowerCase();
	}
}
